---
#
# Setup all required packages
#
- name: APT | Updating the apt cache
  apt:
    update_cache: yes

- name: APT | Setting up logrotate packages
  apt:
    name: "{{ logrotate_package }}"
    state: present
  when: logrotate_enabled